# Generated by Django 5.0.1 on 2024-05-27 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_contact_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
