# Generated by Django 5.0.1 on 2024-06-02 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_author_remove_categories_icon_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='course',
            name='featured_video',
        ),
        migrations.CreateModel(
            name='Learning_Outcomes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.CharField(max_length=500)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.course')),
            ],
        ),
    ]
