# Generated by Django 5.0.1 on 2024-06-02 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_learning_outcomes_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Internships',
        ),
        migrations.RenameModel(
            old_name='Learning_Outcomes',
            new_name='LEARNING_OUTCOMESS',
        ),
    ]
