# Generated by Django 5.0.1 on 2024-06-02 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_contact_us_delete_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='category',
            field=models.CharField(default='Categories', max_length=50),
        ),
    ]
