# Generated by Django 5.0.1 on 2024-06-02 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_contact_us_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LEARNING_OUTCOMESS',
            new_name='LEARNING_OUTCOMES',
        ),
    ]
