# Generated by Django 5.0.1 on 2024-06-03 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_learning_outcomess_learning_outcomes'),
    ]

    operations = [
        migrations.AddField(
            model_name='internships',
            name='modules',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='learning_outcomes',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.internships'),
        ),
    ]
